name: CI

on: [push]

jobs:
  TEST:

    runs-on: windows-latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: '3.6'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:
      - name: Windows setup
        if: runner.os == 'Windows'
        run:
          git config --global core.autocrlf false

      - uses: actions/checkout@v1

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: R Options
        shell: bash
        run: |-
          echo 'MAKE=make -j2' >> .Renviron
          mkdir ~/R_LIB
          echo 'R_LIBS=~/R_LIB' >> .Renviron
          echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> .Rprofile

      - name: Cache R library
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}

      - name: Display PATH
        run: $env:path -split ";"

      - name: Install shiny
        run: Rscript -e "install.packages('shiny')"

      - name: Verify shiny is installed
        run: Rscript -e "print(asNamespace('shiny'))"

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_cran(c('devtools', 'shiny', 'shinytest'))"

      - name: Install shinytest system dependencies
        run: |-
          Rscript -e "shinytest::installDependencies()"

      - name: Run shinytest
        run: |-
          Rscript -e "library(shinytest); expect_pass(testApp('001-hello'))"
          Rscript -e "shinytest::viewTestDiff('001-hello')"

      - name: Create results artifact
        run: tar cvf 001-hello.tar 001-hello/

      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
            name: 001-hello-results
            path: 001-hello.tar
