name: CI

on: [push]

jobs:
  TEST:

    runs-on: windows-latest
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-latest, r: '3.6'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      CRAN: ${{ matrix.config.cran }}

    steps:

      - name: Fix path for Windows caching
        if: runner.os == 'Windows'
        run: echo "::add-path::C:/Program Files/Git/usr/bin"


      - name: Make test directory
        run: mkdir foo


      - name: Cache foo library
        uses: actions/cache@v1
        with:
          path: foo
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-foo


      # - name: Windows setup
      #   if: runner.os == 'Windows'
      #   run:
      #     git config --global core.autocrlf false

      # - uses: actions/checkout@v1

      # - uses: r-lib/actions/setup-r@master
      #   with:
      #     r-version: ${{ matrix.config.r }}

      # - name: R Options
      #   shell: bash
      #   run: |-
      #     echo 'MAKE=make -j2' >> .Renviron
      #     mkdir ~/R_LIB
      #     echo 'R_LIBS=~/R_LIB' >> .Renviron
      #     echo 'options(repos = c(CRAN = "https://cloud.r-project.org"))' >> .Rprofile

      # - name: Cache R library
      #   if: runner.os != 'Windows'
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ env.R_LIBS_USER }}
      #     key: ${{ runner.os }}-r-${{ matrix.config.r }}-${{ hashFiles('**/DESCRIPTION') }}

      # - name: Display PATH
      #   run: $env:path -split ";"

      # - name: Install Packages
      #   run: |-
      #     Rscript -e "install.packages('remotes')"
      #     Rscript -e "remotes::install_cran(c('shiny', 'shinytest'))"

      # - name: Install shinytest system dependencies
      #   run: |-
      #     Rscript -e "shinytest::installDependencies()"

      # - name: Run shinytest
      #   run: |-
      #     Rscript -e "library(shinytest); expect_pass(testApp('001-hello'))"
      #     Rscript -e "shinytest::viewTestDiff('001-hello')"

      # - name: Create plot
      #   run: |-
      #     Rscript -e "png('001-hello/test.png'); plot(1:10, 1:10); dev.off()"
      #     Rscript -e "png('001-hello/test72.png', res=72); plot(1:10, 1:10); dev.off()"

      # - name: Upload test results
      #   uses: actions/upload-artifact@v1
      #   with:
      #       name: 001-hello-results
      #       path: 001-hello
